"""empty message

Revision ID: 63cceea0eab0
Revises: 
Create Date: 2025-06-02 22:06:19.772329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63cceea0eab0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pedidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_cliente', sa.String(length=30), nullable=False),
    sa.Column('telefone', sa.String(length=11), nullable=False),
    sa.Column('local_entrega', sa.String(length=50), nullable=False),
    sa.Column('vlr_entrega', sa.Float(), nullable=False),
    sa.Column('vlr_total', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pedidos_local_entrega'), ['local_entrega'], unique=False)
        batch_op.create_index(batch_op.f('ix_pedidos_nome_cliente'), ['nome_cliente'], unique=False)
        batch_op.create_index(batch_op.f('ix_pedidos_telefone'), ['telefone'], unique=False)
        batch_op.create_index(batch_op.f('ix_pedidos_vlr_entrega'), ['vlr_entrega'], unique=False)
        batch_op.create_index(batch_op.f('ix_pedidos_vlr_total'), ['vlr_total'], unique=False)

    op.create_table('itens_pedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=30), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('vlr_unit', sa.Float(), nullable=False),
    sa.Column('vlr_total', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('itens_pedido', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_itens_pedido_descricao'), ['descricao'], unique=False)
        batch_op.create_index(batch_op.f('ix_itens_pedido_pedido_id'), ['pedido_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_itens_pedido_quantidade'), ['quantidade'], unique=False)
        batch_op.create_index(batch_op.f('ix_itens_pedido_vlr_total'), ['vlr_total'], unique=False)
        batch_op.create_index(batch_op.f('ix_itens_pedido_vlr_unit'), ['vlr_unit'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('itens_pedido', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_itens_pedido_vlr_unit'))
        batch_op.drop_index(batch_op.f('ix_itens_pedido_vlr_total'))
        batch_op.drop_index(batch_op.f('ix_itens_pedido_quantidade'))
        batch_op.drop_index(batch_op.f('ix_itens_pedido_pedido_id'))
        batch_op.drop_index(batch_op.f('ix_itens_pedido_descricao'))

    op.drop_table('itens_pedido')
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pedidos_vlr_total'))
        batch_op.drop_index(batch_op.f('ix_pedidos_vlr_entrega'))
        batch_op.drop_index(batch_op.f('ix_pedidos_telefone'))
        batch_op.drop_index(batch_op.f('ix_pedidos_nome_cliente'))
        batch_op.drop_index(batch_op.f('ix_pedidos_local_entrega'))

    op.drop_table('pedidos')
    # ### end Alembic commands ###
