"""pedidos table

Revision ID: 7ce36f941a50
Revises: 
Create Date: 2025-05-20 21:28:58.396062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ce36f941a50'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('itens_pedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=30), nullable=False),
    sa.Column('vlr_entrega', sa.Float(), nullable=False),
    sa.Column('vlr_total', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('itens_pedido', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_itens_pedido_descricao'), ['descricao'], unique=False)
        batch_op.create_index(batch_op.f('ix_itens_pedido_vlr_entrega'), ['vlr_entrega'], unique=False)
        batch_op.create_index(batch_op.f('ix_itens_pedido_vlr_total'), ['vlr_total'], unique=False)

    op.create_table('pedidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_cliente', sa.String(length=30), nullable=False),
    sa.Column('local_entrega', sa.String(length=50), nullable=False),
    sa.Column('vlr_entrega', sa.Float(), nullable=False),
    sa.Column('vlr_total', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pedidos_local_entrega'), ['local_entrega'], unique=False)
        batch_op.create_index(batch_op.f('ix_pedidos_nome_cliente'), ['nome_cliente'], unique=False)
        batch_op.create_index(batch_op.f('ix_pedidos_vlr_entrega'), ['vlr_entrega'], unique=False)
        batch_op.create_index(batch_op.f('ix_pedidos_vlr_total'), ['vlr_total'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pedidos_vlr_total'))
        batch_op.drop_index(batch_op.f('ix_pedidos_vlr_entrega'))
        batch_op.drop_index(batch_op.f('ix_pedidos_nome_cliente'))
        batch_op.drop_index(batch_op.f('ix_pedidos_local_entrega'))

    op.drop_table('pedidos')
    with op.batch_alter_table('itens_pedido', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_itens_pedido_vlr_total'))
        batch_op.drop_index(batch_op.f('ix_itens_pedido_vlr_entrega'))
        batch_op.drop_index(batch_op.f('ix_itens_pedido_descricao'))

    op.drop_table('itens_pedido')
    # ### end Alembic commands ###
