"""empty message

Revision ID: cf34f1cda34d
Revises: 63cceea0eab0
Create Date: 2025-06-02 22:40:08.439654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf34f1cda34d'
down_revision = '63cceea0eab0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=1), nullable=False))
        batch_op.add_column(sa.Column('criado', sa.TIMESTAMP(), nullable=False))
        batch_op.add_column(sa.Column('modificado', sa.TIMESTAMP(), nullable=False))
        batch_op.create_index(batch_op.f('ix_pedidos_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pedidos_status'))
        batch_op.drop_column('modificado')
        batch_op.drop_column('criado')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
