"""empty message

Revision ID: daa0f10d12f6
Revises: 7ce36f941a50
Create Date: 2025-06-01 15:53:52.378843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'daa0f10d12f6'
down_revision = '7ce36f941a50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('itens_pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pedido_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('quantidade', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('vlr_unit', sa.Float(), nullable=False))
        batch_op.drop_index('ix_itens_pedido_vlr_entrega')
        batch_op.create_index(batch_op.f('ix_itens_pedido_pedido_id'), ['pedido_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_itens_pedido_quantidade'), ['quantidade'], unique=False)
        batch_op.create_index(batch_op.f('ix_itens_pedido_vlr_unit'), ['vlr_unit'], unique=False)
        batch_op.create_foreign_key(None, 'pedidos', ['pedido_id'], ['id'])
        batch_op.drop_column('vlr_entrega')

    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telefone', sa.String(length=11), nullable=False))
        batch_op.create_index(batch_op.f('ix_pedidos_telefone'), ['telefone'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pedidos_telefone'))
        batch_op.drop_column('telefone')

    with op.batch_alter_table('itens_pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vlr_entrega', sa.FLOAT(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_itens_pedido_vlr_unit'))
        batch_op.drop_index(batch_op.f('ix_itens_pedido_quantidade'))
        batch_op.drop_index(batch_op.f('ix_itens_pedido_pedido_id'))
        batch_op.create_index('ix_itens_pedido_vlr_entrega', ['vlr_entrega'], unique=False)
        batch_op.drop_column('vlr_unit')
        batch_op.drop_column('quantidade')
        batch_op.drop_column('pedido_id')

    # ### end Alembic commands ###
